/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Logica.Cola;
import Logica.Node;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crist
 */
public class Menu extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
        private Cola cola;
        private Timer timer;
        private DefaultTableModel modelPendientes;
        private DefaultTableModel modelRecibidos;

        /**
         * Creates new form Menu
         */
        public Menu() {
                initComponents();
                // Inicializar la cola con límite por defecto, por ejemplo 10
                cola = new Cola(10);
                // Inicializar modelos de tablas
                modelPendientes = (DefaultTableModel) jTable1.getModel();
                modelRecibidos = (DefaultTableModel) jTable2.getModel();
                // Limpiar tablas
                modelPendientes.setRowCount(0);
                modelRecibidos.setRowCount(0);
                // Inicializar timer (se configurará con segundos)
                timer = null;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jTextField2 = new javax.swing.JTextField();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextArea2 = new javax.swing.JTextArea();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jScrollPane3 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jScrollPane4 = new javax.swing.JScrollPane();
                jTable2 = new javax.swing.JTable();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setText("Atendiendo los Mensajes");

                jLabel2.setText("Nombre");

                jLabel3.setText("Segundos");

                jTextArea2.setColumns(20);
                jTextArea2.setRows(5);
                jScrollPane2.setViewportView(jTextArea2);

                jButton1.setText("Enviar");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jButton2.setText("Primero Ultimo");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null },
                                                { null, null, null },
                                                { null, null, null },
                                                { null, null, null }
                                },
                                new String[] {
                                                "Mensaje", "Nombre", "Fecha y hora"
                                }));
                jScrollPane3.setViewportView(jTable1);

                jTable2.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null },
                                                { null, null, null },
                                                { null, null, null },
                                                { null, null, null }
                                },
                                new String[] {
                                                "MensajeRecibido", "Nombre", "Fecha Recibido"
                                }));
                jScrollPane4.setViewportView(jTable2);

                jLabel4.setText("Mensajes para antender");

                jLabel5.setText("Mensajes Recibido");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                                .addComponent(jTextField2,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                98,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel2)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jScrollPane2,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addComponent(jTextField1,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                111,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addGap(217, 217,
                                                                                                                                                                                217)
                                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)))))
                                                                                                .addGap(10, 10, 10))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                layout.createSequentialGroup()
                                                                                                                .addComponent(jButton1)
                                                                                                                .addGap(34, 34, 34)
                                                                                                                .addComponent(jButton2)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jScrollPane3,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                240,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                70,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jScrollPane4,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                315,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(12, 12, 12)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel5)
                                                                                                                .addGap(216, 216,
                                                                                                                                216)))
                                                                .addGap(16, 16, 16))
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(227, 227, 227)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(jTextField1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jTextField2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jButton2)
                                                                                .addComponent(jButton1))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                119,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(jLabel5))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jScrollPane4,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                107,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jScrollPane3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                0,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(39, 39, 39)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                        logger.log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JTable jTable1;
        private javax.swing.JTable jTable2;
        private javax.swing.JTextArea jTextArea2;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField2;
        // End of variables declaration//GEN-END:variables

        // boton de envirar con sus comentarios
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
                String nombre = jTextField1.getText().trim();
                String mensaje = jTextArea2.getText().trim();
                String segundosStr = jTextField2.getText().trim();

                // validaciones
                if (nombre.isEmpty() || mensaje.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Por favor, ingrese nombre y mensaje.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                        return;
                }

                // crear nodo
                Node node = new Node(nombre, mensaje);

                // intentar encolar
                if (cola.enqueue(node)) {
                        // actualizar tabla de pendientes
                        actualizarTablaPendientes();
                        // limpiar campos
                        jTextField1.setText("");
                        jTextArea2.setText("");
                        // configurar segundos si se cambio
                        if (!segundosStr.isEmpty()) {
                                try {
                                        int segundos = Integer.parseInt(segundosStr);
                                        // para colocar el tiempo en la cola
                                        cola.setSeconds(segundos);
                                        configurarTimer();
                                } catch (NumberFormatException e) {
                                        JOptionPane.showMessageDialog(this, "Segundos debe ser un número entero.",
                                                        "Error", JOptionPane.ERROR_MESSAGE);
                                }
                        }
                } else {
                        JOptionPane.showMessageDialog(this, "Cola llena", "Alerta", JOptionPane.WARNING_MESSAGE);
                }
        }

        // mostrar primero y el ultimo
        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
                Node first = cola.getFirst();
                Node last = cola.getLast();
                String mensaje = "";
                if (first != null) {
                        mensaje += "Primero: " + first.getNombre() + " - " + first.getMensaje() + "\n";
                } else {
                        mensaje += "Cola vacía\n";
                }
                if (last != null) {
                        mensaje += "Último: " + last.getNombre() + " - " + last.getMensaje();
                }
                JOptionPane.showMessageDialog(this, mensaje, "Primero y Último", JOptionPane.INFORMATION_MESSAGE);
        }

        // funcion para actualizar la tabla de pendientes
        private void actualizarTablaPendientes() {
                modelPendientes.setRowCount(0);
                java.util.List<Node> nodos = cola.getNodos();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                for (Node node : nodos) {
                        modelPendientes.addRow(new Object[] { node.getMensaje(), node.getNombre(),
                                        node.getFechaHoraEnvio().format(formatter) });
                }
        }

        // funcion para configurar el timer
        private void configurarTimer() {
                if (timer != null) {
                        timer.stop();
                }
                int segundos = cola.getSeconds();
                if (segundos > 0) {
                        timer = new Timer(segundos * 1000, e -> atenderMensaje());
                        timer.start();
                }
        }

        // funcion para atender mensaje
        private void atenderMensaje() {
                Node node = cola.dequeue();
                if (node != null) {
                        // agregar a tabla de recibidos
                        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                        String fechaRecibido = LocalDateTime.now().format(formatter);
                        modelRecibidos.addRow(new Object[] { node.getMensaje(), node.getNombre(), fechaRecibido });
                        actualizarTablaPendientes();
                } else {
                        // detener el timer para evitar el bug de alertas repetidas
                        if (timer != null) {
                                timer.stop();
                        }
                        JOptionPane.showMessageDialog(this, "Cola vacía", "Alerta", JOptionPane.WARNING_MESSAGE);
                }
        }
}
